// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Showtimes.Scheduler.Infrastructure.Persistence.EFCore;

#nullable disable

namespace Showtimes.Scheduler.Infrastructure.Persistence.EFCore.Migrations
{
    [DbContext(typeof(SchedulerDbContext))]
    partial class SchedulerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Showtimes.Scheduler.Domain.Model.Movie.Movie", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("char(36)")
                        .HasColumnName("movie_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("smallint")
                        .HasColumnName("duration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.HasKey("MovieId");

                    b.HasIndex("MovieId")
                        .IsUnique();

                    b.ToTable("movie", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
